# Generated by Django 5.0.3 on 2024-04-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='excerpt',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_caption',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='newsandupdate',
            name='excerpt',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='newsandupdate',
            name='image_caption',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
